services:
  - docker
language: c
script:
  - python3 ./configure.py
  - make all
after_success:
  - ./push.sh
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  email: false
