#!/bin/bash

set -e

LABELS=${LABELS:-'--label ustcmirror.images --label org.ustcmirror.images=true'}

case "$1" in
    latest | alpine-3.6 )
        docker build -f "Dockerfile.$1" -t "ustcmirror/lftpsync:$1" $LABELS .
        ;;
    * )
        for i in Dockerfile.*; do
            tag="ustcmirror/lftpsync:${i#*.}"
            docker build -f "$i" -t "$tag" $LABELS .
        done
        ;;
esac
