FROM centos:7
LABEL maintainer="Jian Zeng <anonymousknight96 AT gmail.com>" \
      org.ustcmirror.images=true
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    curl -fLo /usr/local/bin/su-exec https://ftp.lug.ustc.edu.cn/misc/su-exec && chmod +x /usr/local/bin/su-exec && \
    echo "592f25c51d0e4c90945ece8c4fa35018d20a1091ac109c98b66eb95deef211c7 /usr/local/bin/su-exec" | sha256sum -c -
ADD ["entry.sh", "savelog", "/usr/local/bin/"]
VOLUME ["/data", "/log"]
CMD ["/entry.sh"]
