FROM alpine:3.12
LABEL maintainer="Yifan Gao<git AT yfgao.com>" \
      org.ustcmirror.images=true
ADD ["entry.sh", "savelog", "/usr/local/bin/"]
VOLUME ["/data", "/log"]
ENTRYPOINT ["entry.sh"]
RUN apk add --no-cache bash tzdata su-exec && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
