FROM ustcmirror/gitsync
LABEL maintainer="Keyu Tao <taoky AT lug.ustc.edu.cn>"
ADD sync-crates-index.sh /sync-crates-index.sh
ADD crates-index-hook.sh /
ADD upstream.sh /
ENV SYNC_SCRIPT=/sync-crates-index.sh
